version: 2
jobs:
  test_regression_model:
    working_directory: ~/project
    docker:
      - image: circleci/python:3.7.2
    steps:
      - checkout
      - run:
          name: Runnning tests
          command: |
            virtualenv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install -r Part13/packages/regression_model/requirements.txt
            chmod +x ./Part13/scripts/fetch_kaggle_dataset.sh
            ./Part13/scripts/fetch_kaggle_dataset.sh
            py.test -vv Part13/packages/regression_model/tests

workflows:
  version: 2
  test-all:
    jobs:
      - test_regression_model
